# Neural Memory System - PyTorchListStore demo

## Environment setup

In [1]:
import os
from pathlib import Path

In [2]:
CURRENT_FOLDER = Path(os.getcwd())

In [3]:
CD_KEY = "--PYTORCH_LIST_STORE_DEMO_IN_ROOT"

if (
    CD_KEY not in os.environ
    or os.environ[CD_KEY] is None
    or len(os.environ[CD_KEY]) == 0
    or os.environ[CD_KEY] == "false"
):
    %cd -q ../../..
    
    ROOT_FOLDER = Path(os.getcwd()).relative_to(os.getcwd())
    CURRENT_FOLDER = CURRENT_FOLDER.relative_to(ROOT_FOLDER.absolute())
    
os.environ[CD_KEY] = "true"

In [4]:
print(f"Root folder:    {ROOT_FOLDER}")
print(f"Current folder: {CURRENT_FOLDER}")

Root folder:    .
Current folder: demo/components/stores


## Modules

In [5]:
import torch
import torch.nn

In [6]:
from nemesys.modelling.blocks.pytorch_block import PyTorchBlock
from nemesys.modelling.stores.pytorch_list_store import PyTorchListStore

In [7]:
torch.set_printoptions(sci_mode=False)

## Store setup

In [8]:
store = PyTorchListStore()

## Setting values

### Setting all values

In [9]:
block_tensors = [
    torch.normal(mean=0, std=1, size=(3, 4, 5))
    for _ in range(2)
]
blocks = [
    PyTorchBlock.from_tensor(block_tensor)
    for block_tensor in block_tensors
]

In [10]:
store.set_all(blocks)

In [11]:
print(store)

[tensor([[[-0.2300, -0.6651,  0.8999, -1.6332,  2.1068],
         [-0.6748, -0.9371,  1.0201, -2.2129, -0.2126],
         [-1.5771, -0.2148,  0.8784, -1.5063, -0.8381],
         [ 1.4678,  0.0490, -0.4015, -1.7074,  0.5224]],

        [[ 0.5600,  0.9534,  0.3417,  0.7842, -0.6812],
         [ 1.0886,  0.2973, -0.7711, -0.1499,  1.8569],
         [ 0.6571, -1.4816, -1.8590,  0.4241,  0.5162],
         [ 1.7648, -1.8608, -0.3753,  0.2151,  0.3415]],

        [[ 0.2331, -0.4335, -0.2121, -0.6993, -0.0882],
         [ 1.2100,  0.6390, -0.1411, -2.2581, -0.6186],
         [ 0.2593,  1.0203, -0.6357, -0.4740, -0.1554],
         [ 0.5734, -0.1930,  0.0093,  0.6449,  1.5395]]]),
 tensor([[[-0.0718, -0.2678,  1.3636, -2.0246, -0.1990],
         [ 0.9259,  1.4012, -0.9471,  0.8158, -0.5596],
         [ 0.7258, -0.1031,  1.8959, -0.6016, -0.7274],
         [ 1.8471, -0.0792, -0.0352,  0.2223,  0.1337]],

        [[ 1.0280, -0.0393,  0.7101,  0.5207, -1.4708],
         [-0.1918,  0.1151,  0.5490, 

### Setting one value

In [12]:
new_first_tensor = torch.normal(mean=0, std=1, size=(2, 3, 4))
new_first_block = PyTorchBlock.from_tensor(new_first_tensor)

In [13]:
store.set_one(0, new_first_block)

In [14]:
print(store)

[tensor([[[-0.6899, -0.4850, -0.1093, -1.6241],
         [ 1.9250,  1.2041, -0.8849,  0.2110],
         [-0.0484,  1.6537,  1.2840, -2.2416]],

        [[ 0.9564, -0.5794,  0.6733, -0.6792],
         [ 0.1262, -0.3764, -0.5701,  0.1720],
         [-0.0589,  0.9239,  1.7211, -1.4973]]]),
 tensor([[[-0.0718, -0.2678,  1.3636, -2.0246, -0.1990],
         [ 0.9259,  1.4012, -0.9471,  0.8158, -0.5596],
         [ 0.7258, -0.1031,  1.8959, -0.6016, -0.7274],
         [ 1.8471, -0.0792, -0.0352,  0.2223,  0.1337]],

        [[ 1.0280, -0.0393,  0.7101,  0.5207, -1.4708],
         [-0.1918,  0.1151,  0.5490,  1.7493,  0.9857],
         [ 0.6740, -0.3026,  0.6713, -0.5085, -0.0539],
         [-0.5981,  0.5874,  0.6873, -0.8925, -0.4270]],

        [[ 1.2004, -0.2279,  0.2887,  2.1504, -0.0421],
         [-0.1979, -1.5271,  0.0564,  0.7429,  0.0795],
         [ 0.9923, -0.9294, -0.4271,  1.7056, -0.4198],
         [ 0.5661, -0.3081, -0.4512, -0.6877,  0.2229]]])]


### Appending a value

In [15]:
tensor_to_append = torch.normal(mean=0, std=1, size=(1, 2, 3))
block_to_append = PyTorchBlock.from_tensor(tensor_to_append)

In [16]:
store.append(block_to_append)

In [17]:
print(store)

[tensor([[[-0.6899, -0.4850, -0.1093, -1.6241],
         [ 1.9250,  1.2041, -0.8849,  0.2110],
         [-0.0484,  1.6537,  1.2840, -2.2416]],

        [[ 0.9564, -0.5794,  0.6733, -0.6792],
         [ 0.1262, -0.3764, -0.5701,  0.1720],
         [-0.0589,  0.9239,  1.7211, -1.4973]]]),
 tensor([[[-0.0718, -0.2678,  1.3636, -2.0246, -0.1990],
         [ 0.9259,  1.4012, -0.9471,  0.8158, -0.5596],
         [ 0.7258, -0.1031,  1.8959, -0.6016, -0.7274],
         [ 1.8471, -0.0792, -0.0352,  0.2223,  0.1337]],

        [[ 1.0280, -0.0393,  0.7101,  0.5207, -1.4708],
         [-0.1918,  0.1151,  0.5490,  1.7493,  0.9857],
         [ 0.6740, -0.3026,  0.6713, -0.5085, -0.0539],
         [-0.5981,  0.5874,  0.6873, -0.8925, -0.4270]],

        [[ 1.2004, -0.2279,  0.2887,  2.1504, -0.0421],
         [-0.1979, -1.5271,  0.0564,  0.7429,  0.0795],
         [ 0.9923, -0.9294, -0.4271,  1.7056, -0.4198],
         [ 0.5661, -0.3081, -0.4512, -0.6877,  0.2229]]]),
 tensor([[[-2.1109, -0.5020, -0.

### Setting some values

In [18]:
indices_to_set = (0, 1)
tensors_to_set = [
    torch.normal(mean=0, std=1, size=(1, 2, 3))
    for _ in indices_to_set
]
blocks_to_set = [
    PyTorchBlock.from_tensor(tensor_to_set)
    for tensor_to_set in tensors_to_set
]

In [19]:
store.set_some(keys=indices_to_set, contents=blocks_to_set)

In [20]:
print(store)

[tensor([[[ 0.4488,  1.3271,  1.0355],
         [ 0.6735, -0.9447,  0.0946]]]),
 tensor([[[-1.3430, -1.1268,  1.4008],
         [ 0.5672, -1.9257,  0.5478]]]),
 tensor([[[-2.1109, -0.5020, -0.2779],
         [ 1.6220,  0.9113, -0.1192]]])]


## Getting values

### Getting all values

In [21]:
for value in store.get_all():
    print(f"{value}\n\n")

[[[ 0.44879678  1.3270708   1.035487  ]
  [ 0.6734737  -0.9447335   0.09464643]]]


[[[-1.3430144  -1.1267929   1.4008433 ]
  [ 0.56715494 -1.9257079   0.54783046]]]


[[[-2.1109486  -0.5020222  -0.27792957]
  [ 1.6219851   0.9112824  -0.11918018]]]




### Getting one value

In [22]:
print(store.get_one(0))

[[[ 0.44879678  1.3270708   1.035487  ]
  [ 0.6734737  -0.9447335   0.09464643]]]


### Getting some values

In [23]:
for value in store.get_some((1, 2)):
    print(f"{value}\n\n")

[[[-1.3430144  -1.1267929   1.4008433 ]
  [ 0.56715494 -1.9257079   0.54783046]]]


[[[-2.1109486  -0.5020222  -0.27792957]
  [ 1.6219851   0.9112824  -0.11918018]]]




## Removing values

In [24]:
original_store = PyTorchListStore()
original_store.set_all(store.get_all())

### Removing all values

In [25]:
store.remove_all()

In [26]:
print(store)

[]


### Removing one value

In [27]:
store.set_all(original_store.get_all())

In [28]:
print(store)

[tensor([[[ 0.4488,  1.3271,  1.0355],
         [ 0.6735, -0.9447,  0.0946]]]),
 tensor([[[-1.3430, -1.1268,  1.4008],
         [ 0.5672, -1.9257,  0.5478]]]),
 tensor([[[-2.1109, -0.5020, -0.2779],
         [ 1.6220,  0.9113, -0.1192]]])]


In [29]:
store.remove_one(0)

In [30]:
print(store)

[tensor([[[-1.3430, -1.1268,  1.4008],
         [ 0.5672, -1.9257,  0.5478]]]),
 tensor([[[-2.1109, -0.5020, -0.2779],
         [ 1.6220,  0.9113, -0.1192]]])]


### Removing some values

In [31]:
store.set_all(original_store.get_all())

In [32]:
print(store)

[tensor([[[ 0.4488,  1.3271,  1.0355],
         [ 0.6735, -0.9447,  0.0946]]]),
 tensor([[[-1.3430, -1.1268,  1.4008],
         [ 0.5672, -1.9257,  0.5478]]]),
 tensor([[[-2.1109, -0.5020, -0.2779],
         [ 1.6220,  0.9113, -0.1192]]])]


In [33]:
store.remove_some((0, 2))

In [34]:
print(store)

[tensor([[[-1.3430, -1.1268,  1.4008],
         [ 0.5672, -1.9257,  0.5478]]])]
