# Neural Memory System - PyTorchBlock demo

## Environment setup

In [1]:
import os
from pathlib import Path

In [2]:
CURRENT_FOLDER = Path(os.getcwd())

In [3]:
CD_KEY = "--PYTORCH_BLOCK_DEMO_IN_ROOT"

if (
    CD_KEY not in os.environ
    or os.environ[CD_KEY] is None
    or len(os.environ[CD_KEY]) == 0
    or os.environ[CD_KEY] == "false"
):
    %cd -q ../../..
    
    ROOT_FOLDER = Path(os.getcwd()).relative_to(os.getcwd())
    CURRENT_FOLDER = CURRENT_FOLDER.relative_to(ROOT_FOLDER.absolute())
    
os.environ[CD_KEY] = "true"

In [4]:
print(f"Root folder:    {ROOT_FOLDER}")
print(f"Current folder: {CURRENT_FOLDER}")

Root folder:    .
Current folder: demo/components/blocks


## Modules

In [5]:
import torch
import torch.nn

In [6]:
from nemesys.modelling.blocks.pytorch_block import PyTorchBlock

In [7]:
torch.set_printoptions(sci_mode=False)

## Block setup

In [8]:
base_shape = (3, 4)
dtype = "float32"
device = "cpu"

In [9]:
block = PyTorchBlock(
    base_shape=base_shape,
    dtype=dtype,
    device=device
)

In [10]:
print(f"Base shape: {block.base_shape}")
print(block)

Base shape: (3, 4)
[]


### Getting block default

In [11]:
block_default = block.default()

In [12]:
print(f"Base shape: {block_default.base_shape}")
print(block)

Base shape: (3, 4)
[]


### Initializing from tensors

In [13]:
imported_block = PyTorchBlock.from_tensor(torch.normal(mean=0, std=1, size=(1, 3, 4)))

In [14]:
print(imported_block)

[[[ 0.31728265  1.4025906  -0.17126203  0.77893245]
  [ 0.88134867 -0.90505886 -1.5496457   0.41465402]
  [-0.20294653 -0.8180233   0.09069518  1.2958885 ]]]


### Cloning blocks

In [15]:
cloned_block = imported_block.clone()

In [16]:
print(cloned_block)

[[[ 0.31728265  1.4025906  -0.17126203  0.77893245]
  [ 0.88134867 -0.90505886 -1.5496457   0.41465402]
  [-0.20294653 -0.8180233   0.09069518  1.2958885 ]]]


In [17]:
print(f"Same reference: {imported_block is cloned_block}")
print(f"Same value: {imported_block == cloned_block}")

Same reference: False
Same value: False


In [18]:
print(f"Same data referenced: {imported_block.data is cloned_block.data}")
print(f"Same data values: {imported_block.data == cloned_block.data}")

Same data referenced: False
Same data values: tensor([[[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]])
