# Neural Memory System - PyTorchDecoderConv2D demo

## Environment setup

In [1]:
import os
from pathlib import Path

In [2]:
CURRENT_FOLDER = Path(os.getcwd())

In [3]:
CD_KEY = "--PYTORCH_DECODER_CONV2D_DEMO_IN_ROOT"

if (
    CD_KEY not in os.environ
    or os.environ[CD_KEY] is None
    or len(os.environ[CD_KEY]) == 0
    or os.environ[CD_KEY] == "false"
):
    %cd -q ../../..
    
    ROOT_FOLDER = Path(os.getcwd()).relative_to(os.getcwd())
    CURRENT_FOLDER = CURRENT_FOLDER.relative_to(ROOT_FOLDER.absolute())
    
os.environ[CD_KEY] = "true"

In [4]:
print(f"Root folder:    {ROOT_FOLDER}")
print(f"Current folder: {CURRENT_FOLDER}")

Root folder:    .
Current folder: demo/components/decoders


## Modules

In [5]:
import math

In [6]:
import torch
import torch.nn

In [7]:
from nemesys.modelling.blocks.pytorch_block import PyTorchBlock
from nemesys.modelling.decoders.modules.pytorch_decoder_conv2d import PyTorchDecoderConv2D
from nemesys.modelling.stores.pytorch_list_store import PyTorchListStore

In [8]:
torch.set_printoptions(sci_mode=False)

## Store setup

In [9]:
store = PyTorchListStore()

In [10]:
n_blocks = 5
n_shapes_per_block_interval = (1, 3)
base_shape = (3, 4)

In [11]:
block_tensors = [
    torch.normal(mean=0, std=1, size=(n_shapes, *base_shape))
    for n_shapes in torch.randint(*n_shapes_per_block_interval, (n_blocks,))
]

In [12]:
blocks = [
    PyTorchBlock.from_tensor(block_tensor)
    for block_tensor in block_tensors
]

In [13]:
store.set_all(blocks)

In [14]:
print(store)

[tensor([[[-0.2768, -0.4237,  1.1168, -2.6320],
         [ 1.2782,  0.6363, -0.4488,  0.5287],
         [ 0.8698, -0.9242, -1.0456,  0.8315]],

        [[-0.0737, -0.0691, -0.3661, -1.2948],
         [-0.5853,  0.4625,  2.0179,  1.3274],
         [-0.9873, -0.1482,  0.4677,  0.2914]]]),
 tensor([[[ 1.5072, -0.0156, -1.5723, -0.9636],
         [ 1.0055,  0.8238, -2.7285,  0.7499],
         [-0.6132,  0.5981, -1.8857,  2.0812]],

        [[ 0.3369, -0.5577, -1.1800,  0.9843],
         [ 0.7493, -0.1581, -0.3657, -1.1130],
         [ 1.0964, -1.0983, -0.9802,  1.1958]]]),
 tensor([[[ 1.1391,  0.7812, -2.0493, -0.0540],
         [-0.3671, -0.4420, -0.1300, -1.0198],
         [-0.9384, -0.0403, -0.3097,  1.5668]]]),
 tensor([[[ 0.7676,  2.1379,  0.1144, -0.5096],
         [-0.3462,  1.2244, -0.3620, -1.2454],
         [-0.5277,  2.3552,  0.9707, -0.0582]],

        [[-1.3268, -1.3440,  0.0427,  0.5252],
         [ 0.9843, -0.5161,  1.0801,  0.1506],
         [-0.8568,  0.3377, -1.0494, -0.8

## Decoder setup

In [15]:
in_channels = 1
out_channels = 4

window_length = 3

In [16]:
decoder = PyTorchDecoderConv2D(
    in_channels = in_channels,
    out_channels = out_channels,
    kernel_size = (window_length, math.prod(base_shape))
)

## Results

In [17]:
result = decoder(store)

In [18]:
print(result)

{'content': tensor([[[[     0.0511],
          [    -1.1183],
          [    -0.7146],
          [    -0.4854],
          [    -0.7013],
          [    -0.6692],
          [    -0.1796]],

         [[    -0.8493],
          [    -0.1077],
          [    -0.7488],
          [     0.2027],
          [    -0.0007],
          [     0.7154],
          [    -0.5636]],

         [[    -0.0723],
          [     0.0273],
          [    -0.0062],
          [    -0.4032],
          [     0.3041],
          [    -0.4063],
          [    -0.0484]],

         [[     0.8434],
          [    -0.7737],
          [     0.2703],
          [     1.3030],
          [    -1.0452],
          [     0.9108],
          [    -0.2948]]]], grad_fn=<ThnnConv2DBackward>)}
